version: '3'

services:
  database:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5435:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  timescale_cli:
    build: ./
    depends_on:
      - "database"
    links:
      - "database"
    restart: always